{
 "title": "iot monitoreo",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Promedio de ruido (Histórico)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"noise_db\") FROM noise_measurements\n"
    }
   ]
  },
  {
   "title": "Calidad Actual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"quality\") \nFROM \"noise_measurements\"\nWHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "Ruido actual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"noise_db\")\nFROM \"noise_measurements\"\nWHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "max dB | min dB | avg dB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "SELECT \"noise_db\"\nFROM \"noise_measurements\"\nWHERE $timeFilter\nGROUP BY \"device\"\n"
    },
    {
     "query": "SELECT max(\"max_db\") AS \"max_db\", min(\"min_db\") AS \"min_db\"\nFROM \"noise_measurements\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "avg dB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "SELECT \"noise_db\"\nFROM \"noise_measurements\"\nWHERE $timeFilter\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Histórico por horas (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "SELECT mean(\"noise_db\")\nFROM noise_measurements\nGROUP BY time(60m)\n"
    }
   ]
  },
  {
   "title": "Histórico por horas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "SELECT mean(noise_db)\nFROM noise_measurements\nGROUP BY time(1h) fill(null)\n"
    }
   ]
  }
 ]
}